Repository fastcam-sideproject/FE-master-plan-b, pull requests merged in 2025-01, with the labels that each got.

#3 feat: button 추가
  src/app/layout.tsx
  src/app/page.tsx
  src/components/MswWrapper.tsx
  src/components/ui/button.tsx
Labels: feat, style

#7 feat: FAB 컴포넌트 추가
  package-lock.json
  package.json
  src/app/page.tsx
  src/components/FAB/Fab.tsx
  src/components/MswWrapper.tsx
Labels: feat, style

#9 feat: breadcrumb 컴포넌트 추가
  src/app/page.tsx
  src/components/ui/breadcrumb.tsx
  src/lib/common/FAB/Fab.tsx
Labels: feat, style

#13 feat: NumberPagination 컴포넌트 추가
  src/app/page.tsx
  src/components/NumberPagination.tsx
  src/components/ui/button.tsx
  src/components/ui/pagination.tsx
Labels: feat, style

#15 feat : 헤더 와 로고 추가
  public/logos/logo-dark.svg
  public/logos/logo-light.png
  public/logos/logo-light.svg
  public/logos/logo-text-dark.svg
  public/logos/logo-text-light.svg
  src/app/layout.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.tsx
Labels: feat, style

#17 feat: table 컴포넌트 생성
  src/app/page.tsx
  src/components/NumberPagination.tsx
  src/components/ui/table.tsx
  src/lib/common/CertificateTable/CertificateTable.tsx
  src/lib/common/CertificateTable/index.ts
  tailwind.config.ts
Labels: feat

#18 style: table 컴포넌트 스타일 수정
  src/app/page.tsx
  src/components/ui/table.tsx
  src/lib/common/CertificateTable/CertificateTable.tsx
Labels: style

#24 feat: NumberInput 컴포넌트 추가
  src/app/page.tsx
  src/components/ui/input.tsx
  src/lib/common/NumberInput/NumberInput.tsx
  src/lib/common/NumberInput/index.ts
Labels: feat

#31 style: breadcrumb 컴포넌트 css 수정
  src/app/page.tsx
  src/components/ui/breadcrumb.tsx
Labels: style

#32 feat: PageHeader 컴포넌트 추가
  src/app/page.tsx
  src/components/ui/breadcrumb.tsx
  src/lib/common/PageHeader/PageHeader.tsx
  src/lib/common/PageHeader/index.ts
Labels: feat

#34 feat: ContentsHeader 컴포넌트 추가
  src/app/page.tsx
  src/components/ContentsHeader.tsx
Labels: feat

#16 feat: text-button 추가 및 secondary-button 아이콘 추가
  src/app/page.tsx
  src/components/ui/button.tsx
Labels: feat

#46 feat: Avatar 컴포넌트 추가
  src/app/page.tsx
  src/lib/common/Avatar/Avatar.tsx
  src/lib/common/Avatar/index.ts
Labels: feat, style

#49 refactor : Icon 라이브러리로 수정
  src/components/Header/Header.tsx
  src/components/SideBar/SideBarFavoriteCertifications.tsx
  src/components/SideBar/SideBarLi.tsx
  src/components/SideBar/SideBarLogo.tsx
  src/components/SideBar/SideBarMyHome.tsx
Labels: refactor

#53 feat: dropdown 컴포넌트 구현
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.ts
  src/components/ui/dropdown-menu.tsx
  tailwind.config.ts
Labels: feat, style

#60 feat: tooltip 컴포넌트 추가
  src/app/page.tsx
  src/components/common/TooltipComponent.tsx
  src/components/ui/tooltip.tsx
Labels: feat, style

#61 feat : tab 컴포넌트 완성
  src/app/page.tsx
  src/components/common/Tab/TabButton.tsx
  src/components/common/Tab/TabHorizon.tsx
  src/components/common/Tab/TabHorizonButton.tsx
  src/components/common/Tab/TabHorizonMedium.tsx
  src/components/common/Tab/TabHorizonSmall.tsx
  src/components/common/Tab/TabVertical.tsx
  src/components/common/Tab/TabVerticalSmall.tsx
  src/components/common/Tab/types.ts
Labels: feat

#66 feat: searchbar 컴포넌트 반응형 추가
  src/components/SearchBar/SearchBar.tsx
Labels: style
